-- MySQL Script generated by MySQL Workbench
-- 12/28/14 23:28:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Property_Project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Property_Project` (
  `I_SeqID` INT NOT NULL,
  `I_Property_Project_ID` INT NOT NULL,
  `D_Input_Date` DATETIME NOT NULL,
  `I_FK_Input_User_ID` INT NOT NULL,
  `I_Update_Delete_Flag` TINYINT(2) NOT NULL,
  `D_Update_Date` DATETIME NOT NULL,
  `I_FK_Update_User_ID` INT NOT NULL,
  `S_Update_Reason` VARCHAR(45) NULL,
  `D_Incoming_Date` DATETIME NULL,
  `S_Incoming_Reason` VARCHAR(45) NULL,
  `S_Incoming_Source` VARCHAR(45) NULL,
  `D_Outgoing_Date` DATETIME NULL,
  `S_Outgoing_Reason` VARCHAR(45) NULL,
  `S_Outgoing_Target` VARCHAR(45) NULL,
  `S_Project_Name` VARCHAR(45) NULL,
  `S_Project_Type` VARCHAR(45) NULL,
  `S_Land_Usage_Type` VARCHAR(45) NULL,
  `F_Land_Area` DOUBLE NULL,
  `S_Comment` VARCHAR(250) NULL,
  PRIMARY KEY (`I_SeqID`, `I_Property_Project_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Property_Building`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Property_Building` (
  `I_SeqID` INT NOT NULL,
  `I_Property_Building_ID` INT NOT NULL,
  `D_Input_Date` DATETIME NOT NULL,
  `I_FK_Input_User_ID` INT NOT NULL,
  `I_Update_Delete_Flag` TINYINT(2) NOT NULL,
  `D_Update_Date` DATETIME NOT NULL,
  `I_FK_Update_User_ID` INT NOT NULL,
  `S_Update_Reason` VARCHAR(45) NULL,
  `D_Incoming_Date` DATETIME NULL,
  `S_Incoming_Reason` VARCHAR(45) NULL,
  `S_Incoming_Source` VARCHAR(45) NULL,
  `D_Outgoing_Date` DATETIME NULL,
  `S_Outgoing_Reason` VARCHAR(45) NULL,
  `S_Outgoing_Target` VARCHAR(45) NULL,
  `S_Road_Name` VARCHAR(45) NULL,
  `S_Street_Number` VARCHAR(45) NULL,
  `S_Address` VARCHAR(45) NULL,
  `I_Finished_Year` TINYINT(4) NULL,
  `F_Land_Area` DOUBLE NULL,
  `S_Land_Type` VARCHAR(45) NULL,
  `F_Building_Area` DOUBLE NULL,
  `I_Levels_Surface` TINYINT(3) NULL,
  `I_Levels_Under` TINYINT(3) NULL,
  `S_Structure` VARCHAR(45) NULL,
  `S_Structure_Type` VARCHAR(45) NULL,
  `S_Comment` VARCHAR(250) NULL,
  PRIMARY KEY (`I_SeqID`, `I_Property_Building_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Property_Unit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Property_Unit` (
  `I_SeqID` INT NOT NULL,
  `I_Property_Unit_ID` INT NOT NULL,
  `D_Input_Date` DATETIME NOT NULL,
  `I_FK_Input_User_ID` INT NOT NULL,
  `I_Update_Delete_Flag` TINYINT(2) NOT NULL,
  `D_Update_Date` DATETIME NOT NULL,
  `I_FK_Update_User_ID` INT NOT NULL,
  `S_Update_Reason` VARCHAR(45) NULL,
  `D_Incoming_Date` DATETIME NULL,
  `S_Incoming_Reason` VARCHAR(45) NULL,
  `S_Incoming_Source` VARCHAR(45) NULL,
  `D_Outgoing_Date` DATETIME NULL,
  `S_Outgoing_Reason` VARCHAR(45) NULL,
  `S_Outgoing_Target` VARCHAR(45) NULL,
  `S_Road_Name` VARCHAR(45) NULL,
  `S_Street_Number` VARCHAR(45) NULL,
  `S_Room_Number` VARCHAR(45) NULL,
  `F_Structure_Area` DOUBLE NULL,
  `F_Build_Area` DOUBLE NULL,
  `F_Loft_Area` DOUBLE NULL,
  `F_Balcony_Area` DOUBLE NULL,
  `F_Basement_Area` DOUBLE NULL,
  `S_Property_Right_Type` VARCHAR(45) NULL,
  `S_Property_Owner` VARCHAR(45) NULL,
  `S_Property_Cert` VARCHAR(45) NULL,
  `S_Certificate_Date` DATETIME NULL,
  `S_Land_Usage_Type` VARCHAR(45) NULL,
  `S_Property_Usage` VARCHAR(45) NULL,
  `S_Unlisted_Tag` VARCHAR(45) NULL,
  `S_Comment` VARCHAR(250) NULL,
  PRIMARY KEY (`I_SeqID`, `I_Property_Unit_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Book_Cost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Book_Cost` (
  `I_SeqID` INT NOT NULL,
  `I_Book_Cost_ID` INT NOT NULL,
  `D_Input_Date` DATETIME NOT NULL,
  `I_FK_Input_User_ID` INT NOT NULL,
  `I_Update_Delete_Flag` TINYINT(2) NOT NULL,
  `D_Update_Date` DATETIME NOT NULL,
  `I_FK_Update_User_ID` INT NOT NULL,
  `S_Update_Reason` VARCHAR(45) NULL,
  `I_Property_Type` TINYINT(1) NULL,
  `I_FK_Property_ID` INT NULL,
  `D_Cost_Date` DATETIME NULL,
  `S_Cost_Reason` VARCHAR(45) NULL,
  `S_Cost_Type` VARCHAR(45) NULL,
  `F_Cost_Amount` DOUBLE NULL,
  `S_Comment` VARCHAR(250) NULL,
  PRIMARY KEY (`I_SeqID`, `I_Book_Cost_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`File_Record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`File_Record` (
  `I_SeqID` INT NOT NULL,
  `I_File_Record_ID` INT NOT NULL,
  `D_Input_Date` DATETIME NOT NULL,
  `I_FK_Input_User_ID` INT NOT NULL,
  `I_Update_Delete_Flag` TINYINT(2) NOT NULL,
  `D_Update_Date` DATETIME NOT NULL,
  `I_FK_Update_User_ID` INT NOT NULL,
  `S_Update_Reason` VARCHAR(45) NULL,
  `I_Property_Type` TINYINT(1) NULL,
  `I_FK_Property_ID` INT NULL,
  `S_File_Record_Number` VARCHAR(45) NULL,
  `D_File_Date` DATETIME NULL,
  `S_File_Reason` VARCHAR(45) NULL,
  `S_File_Source` VARCHAR(45) NULL,
  `D_Unregister_Date` DATETIME NULL,
  `S_Unregister_Reason` VARCHAR(45) NULL,
  `S_File_Name` VARCHAR(45) NULL,
  `S_File_Type` VARCHAR(45) NULL,
  `I_File_Quantity` INT NULL,
  `I_If_Origin` TINYINT(1) NULL,
  `S_Comment` VARCHAR(250) NULL,
  PRIMARY KEY (`I_SeqID`, `I_File_Record_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Assets_Evaluation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Assets_Evaluation` (
  `I_SeqID` INT NOT NULL,
  `I_Asset_Evaluation_ID` INT NOT NULL,
  `D_Input_Date` DATETIME NOT NULL,
  `I_FK_Input_User_ID` INT NOT NULL,
  `I_Update_Delete_Flag` TINYINT(2) NOT NULL,
  `D_Update_Date` DATETIME NOT NULL,
  `I_FK_Update_User_ID` INT NOT NULL,
  `S_Update_Reason` VARCHAR(45) NULL,
  `I_Property_Type` TINYINT(1) NULL,
  `I_FK_Property_ID` INT NULL,
  `S_Evaluation_Report_Number` VARCHAR(45) NULL,
  `D_Evaluation_Date` DATETIME NULL,
  `S_Evaluation_Reason` VARCHAR(45) NULL,
  `S_Evalation_Company` VARCHAR(45) NULL,
  `S_Evaluation_Time_Point` VARCHAR(45) NULL,
  `F_Evaluation_Unit_Price` DOUBLE NULL,
  `F_Evaluation_Total_Price` DOUBLE NULL,
  `F_Evaluation_Cost` DOUBLE NULL,
  `S_Comment` VARCHAR(250) NULL,
  PRIMARY KEY (`I_SeqID`, `I_Asset_Evaluation_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Consignation_Contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Consignation_Contract` (
  `I_SeqID` INT NOT NULL,
  `I_Consignation_Contract_ID` INT NOT NULL,
  `D_Input_Date` DATETIME NOT NULL,
  `I_FK_Input_User_ID` INT NOT NULL,
  `I_Update_Delete_Flag` TINYINT(2) NOT NULL,
  `D_Update_Date` DATETIME NOT NULL,
  `I_FK_Update_User_ID` INT NOT NULL,
  `S_Update_Reason` VARCHAR(45) NULL,
  `I_Property_Type` TINYINT(1) NULL,
  `I_FK_Property_ID` INT NULL,
  `S_Consignation_Contract_Number` VARCHAR(45) NULL,
  `S_Consigned_Company` VARCHAR(45) NULL,
  `D_Consignation_Due_Date` DATETIME NULL,
  `S_Consignation_Project` VARCHAR(45) NULL,
  `S_Consignation_Mgt_Target` VARCHAR(45) NULL,
  `S_Consignation_Run_Target` VARCHAR(45) NULL,
  `F_Consignation_Cost` DOUBLE NULL,
  `S_Payment_Type` VARCHAR(45) NULL,
  `S_Exam_Time_Point` VARCHAR(45) NULL,
  `S_Exam_Key_Point` VARCHAR(45) NULL,
  `S_Comment` VARCHAR(250) NULL,
  PRIMARY KEY (`I_SeqID`, `I_Consignation_Contract_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Leasing_Contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Leasing_Contract` (
  `I_SeqID` INT NOT NULL,
  `I_Leasing_Contract_ID` INT NOT NULL,
  `D_Input_Date` DATETIME NOT NULL,
  `I_FK_Input_User_ID` INT NOT NULL,
  `I_Update_Delete_Flag` TINYINT(2) NOT NULL,
  `D_Update_Date` DATETIME NOT NULL,
  `I_FK_Update_User_ID` INT NOT NULL,
  `S_Update_Reason` VARCHAR(45) NULL,
  `I_Property_Type` TINYINT(1) NULL,
  `I_FK_Property_ID` INT NULL,
  `S_Leasing_Contract_Number` VARCHAR(45) NULL,
  `S_Leasing_Company` VARCHAR(45) NULL,
  `D_Leasing_Due_Date` DATETIME NULL,
  `S_Leasing_Usage` VARCHAR(45) NULL,
  `F_Leasing_Area` DOUBLE NULL,
  `F_Leasing_Unit_Price` DOUBLE NULL,
  `F_Monthly_Rental` DOUBLE NULL,
  `F_Annual_Rental` DOUBLE NULL,
  `D_Free_Due_Date` DATETIME NULL,
  `F_Deposit` DOUBLE NULL,
  `D_Accept_Date` DATETIME NULL,
  `F_Accept_Criteria` VARCHAR(45) NULL,
  `S_Collect_Frequency` VARCHAR(45) NULL,
  `D_Collect_Date` DATETIME NULL,
  `S_Rental_Increment` VARCHAR(45) NULL,
  `S_Property_Agreement` VARCHAR(45) NULL,
  `S_Park_Agreement` VARCHAR(45) NULL,
  `S_Electric_Agreement` VARCHAR(45) NULL,
  `S_Other_Agreement` VARCHAR(45) NULL,
  `S_Comment` VARCHAR(250) NULL,
  PRIMARY KEY (`I_SeqID`, `I_Leasing_Contract_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rental_Planned`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rental_Planned` (
  `I_SeqID` INT NOT NULL,
  `I_Rental_Planned_ID` INT NOT NULL,
  `D_Input_Date` DATETIME NOT NULL,
  `I_FK_Input_User_ID` INT NOT NULL,
  `I_Update_Delete_Flag` TINYINT(2) NOT NULL,
  `D_Update_Date` DATETIME NOT NULL,
  `I_FK_Update_User_ID` INT NOT NULL,
  `S_Update_Reason` VARCHAR(45) NULL,
  `I_Property_Type` TINYINT(1) NULL,
  `I_FK_Property_ID` INT NULL,
  `I_FK_Leasing_Contract_ID` INT NULL,
  `D_Due_Date` DATETIME NULL,
  `F_Due_Amount` DOUBLE NULL,
  `S_Comment` VARCHAR(250) NULL,
  PRIMARY KEY (`I_SeqID`, `I_Rental_Planned_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rental_Actual`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rental_Actual` (
  `I_SeqID` INT NOT NULL,
  `I_Rental_Actual_ID` INT NOT NULL,
  `D_Input_Date` DATETIME NOT NULL,
  `I_FK_Input_User_ID` INT NOT NULL,
  `I_Update_Delete_Flag` TINYINT(2) NOT NULL,
  `D_Update_Date` DATETIME NOT NULL,
  `I_FK_Update_User_ID` INT NOT NULL,
  `S_Update_Reason` VARCHAR(45) NULL,
  `I_Property_Type` TINYINT(1) NULL,
  `I_FK_Property_ID` INT NULL,
  `I_FK_Leasing_Contract_ID` INT NULL,
  `D_Collect_Date` DATETIME NULL,
  `F_Collect_Amount` DOUBLE NULL,
  `S_Comment` VARCHAR(250) NULL,
  PRIMARY KEY (`I_SeqID`, `I_Rental_Actual_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Consignation_Feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Consignation_Feedback` (
  `I_SeqID` INT NOT NULL,
  `I_Consignation_Feedback_ID` INT NOT NULL,
  `D_Input_Date` DATETIME NOT NULL,
  `I_FK_Input_User_ID` INT NOT NULL,
  `I_Update_Delete_Flag` TINYINT(2) NOT NULL,
  `D_Update_Date` DATETIME NOT NULL,
  `I_FK_Update_User_ID` INT NOT NULL,
  `S_Update_Reason` VARCHAR(45) NULL,
  `I_FK_Consignation_Contract_ID` INT NULL,
  `S_To_Company` VARCHAR(45) NULL,
  `S_From_Company` VARCHAR(45) NULL,
  `D_Feedback_Date` DATETIME NULL,
  `S_Feedback_Period` VARCHAR(45) NULL,
  `S_Feedback_Content` VARCHAR(45) NULL,
  `I_Feedback_Level` TINYINT(1) NULL,
  `S_Comment` VARCHAR(250) NULL,
  PRIMARY KEY (`I_SeqID`, `I_Consignation_Feedback_ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
