-- MySQL Script generated by MySQL Workbench
-- 01/02/15 23:28:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema assets_management
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `assets_management` ;

-- -----------------------------------------------------
-- Schema assets_management
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `assets_management` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `assets_management` ;

-- -----------------------------------------------------
-- Table `assets_management`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `assets_management`.`User` ;

CREATE TABLE IF NOT EXISTS `assets_management`.`User` (
  `S_User_Name` VARCHAR(40) NOT NULL,
  `S_Disp_Name` VARCHAR(45) NOT NULL,
  `S_Company_Name` VARCHAR(45) NOT NULL,
  `S_Email` VARCHAR(255) NULL,
  `I_Role_Type` TINYINT(1) NOT NULL,
  `D_Create_Time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `S_Password` VARCHAR(50) NOT NULL,
  `D_Last_Reset_Time` TIMESTAMP NULL,
  PRIMARY KEY (`S_User_Name`),
  UNIQUE INDEX `S_User_Name_UNIQUE` (`S_User_Name` ASC));


-- -----------------------------------------------------
-- Table `assets_management`.`Asset_Info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `assets_management`.`Asset_Info` ;

CREATE TABLE IF NOT EXISTS `assets_management`.`Asset_Info` (
  `I_SeqID` INT NOT NULL DEFAULT 0,
  `I_Asset_ID` INT NOT NULL DEFAULT 0,
  `D_Input_Date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `S_FK_Input_User_Name` VARCHAR(40) NOT NULL,
  `I_Update_Delete_Flag` TINYINT(1) NOT NULL DEFAULT 0,
  `D_Update_Date` TIMESTAMP NULL,
  `S_FK_Update_User_Name` VARCHAR(40) NOT NULL,
  `S_Update_Reason` VARCHAR(45) NULL,
  `D_Incoming_Date` TIMESTAMP NULL,
  `S_Incoming_Reason` VARCHAR(45) NULL,
  `S_Incoming_Source` VARCHAR(45) NULL,
  `D_Outgoing_Date` TIMESTAMP NULL,
  `S_Outgoing_Reason` VARCHAR(45) NULL,
  `S_Outgoing_Target` VARCHAR(45) NULL,
  `I_Asset_Type` TINYINT(1) NOT NULL DEFAULT 0,
  `S_Project_Name` VARCHAR(45) NULL,
  `S_Project_Type` VARCHAR(45) NULL,
  `S_Usage_Type` VARCHAR(45) NULL,
  `F_Usage_Area` DOUBLE NULL,
  `S_Road_Name` VARCHAR(45) NULL,
  `S_Street_Number` VARCHAR(45) NULL,
  `S_Address` VARCHAR(45) NULL,
  `I_Finished_Year` TINYINT(4) NULL,
  `F_Land_Area` DOUBLE NULL,
  `S_Land_Type` VARCHAR(45) NULL,
  `F_Building_Area` DOUBLE NULL,
  `I_Levels_Surface` TINYINT(3) NULL,
  `I_Levels_Under` TINYINT(3) NULL,
  `S_Structure` VARCHAR(45) NULL,
  `S_Structure_Type` VARCHAR(45) NULL,
  `S_Room_Number` VARCHAR(45) NULL,
  `F_Structure_Area` DOUBLE NULL,
  `F_Build_Area` DOUBLE NULL,
  `F_Loft_Area` DOUBLE NULL,
  `F_Balcony_Area` DOUBLE NULL,
  `F_Basement_Area` DOUBLE NULL,
  `S_Property_Right_Type` VARCHAR(45) NULL,
  `S_Property_Owner` VARCHAR(45) NULL,
  `S_Property_Cert` VARCHAR(45) NULL,
  `S_Certificate_Date` DATETIME NULL,
  `S_Land_Usage_Type` VARCHAR(45) NULL,
  `S_Property_Usage` VARCHAR(45) NULL,
  `S_Unlisted_Tag` VARCHAR(45) NULL,
  `S_Comment` VARCHAR(250) NULL,
  PRIMARY KEY (`I_SeqID`, `I_Asset_ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
